import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { resolve } from 'path'

export default defineConfig({
  plugins: [react()],
  base: '/znarnia/',
  build: {
    rollupOptions: {
      input: {
        main: resolve(__dirname, 'index.html'),
        leto2026: resolve(__dirname, 'leto2026/index.html'),
        nachalka: resolve(__dirname, 'nachalka/index.html'),
        partner: resolve(__dirname, 'partner/index.html'),
        'post-leto': resolve(__dirname, 'post-leto/index.html'),
        'post-kanikuly': resolve(__dirname, 'post-kanikuly/index.html'),
        srednyaya: resolve(__dirname, 'srednyaya/index.html'),
        teens: resolve(__dirname, 'teens/index.html'),
        'oplata-srednyaya': resolve(__dirname, 'oplata-srednyaya/index.html'),
        'oplata': resolve(__dirname, 'oplata/index.html'),
        'oplata-nachalka': resolve(__dirname, 'oplata-nachalka/index.html'),
        'topics-nachalka': resolve(__dirname, 'topics-nachalka/index.html'),
        'topics-srednyaya': resolve(__dirname, 'topics-srednyaya/index.html'),
        'russian': resolve(__dirname, 'russian/index.html'),
        'info': resolve(__dirname, 'info/index.html'),
        'banner': resolve(__dirname, 'banner/index.html'),
        'courses': resolve(__dirname, 'courses/index.html'),
        'diagnostika': resolve(__dirname, 'diagnostika/index.html'),
        'diagnostika2': resolve(__dirname, 'diagnostika2/index.html'),
        'sobranie': resolve(__dirname, 'sobranie/index.html'),
        'sobranie-thanks': resolve(__dirname, 'sobranie-thanks/index.html'),
        'probniy-urok': resolve(__dirname, 'probniy-urok/index.html'),
        'probniy-urok-2': resolve(__dirname, 'probniy-urok-2/index.html'),
        'diagnostika-finalnaya': resolve(__dirname, 'diagnostika-finalnaya/index.html'),
        'diagnostika-finalnaya-2': resolve(__dirname, 'diagnostika-finalnaya-2/index.html'),
        'diagnostika-podarok': resolve(__dirname, 'diagnostika-podarok/index.html'),
        'letnie-kursy': resolve(__dirname, 'letnie-kursy/index.html'),
        'letnie-kursy-2': resolve(__dirname, 'letnie-kursy-2/index.html'),
        'glavnaya': resolve(__dirname, 'glavnaya/index.html'),
        'oge-dlya-glavnoy': resolve(__dirname, 'oge-dlya-glavnoy/index.html'),
        'predszapis-osen': resolve(__dirname, 'predszapis-osen/index.html'),
        'predszapis-osen-novye': resolve(__dirname, 'predszapis-osen-novye/index.html'),
        'predszapis-osen-novye-2': resolve(__dirname, 'predszapis-osen-novye-2/index.html'),
        'predszapis-osen-3-podarka': resolve(__dirname, 'predszapis-osen-3-podarka/index.html'),
        'predszapis-osen-2': resolve(__dirname, 'predszapis-osen-2/index.html'),
        'predszapis-osen-srednyaya': resolve(__dirname, 'predszapis-osen-srednyaya/index.html'),
        'predszapis-osen-stariye-5-8': resolve(__dirname, 'predszapis-osen-stariye-5-8/index.html'),
        'predszapis-osen-stariye-9': resolve(__dirname, 'predszapis-osen-stariye-9/index.html'),
        'predszapis-osen-ege-10': resolve(__dirname, 'predszapis-osen-ege-10/index.html'),
        'predszapis-osen-ege-profilnoe': resolve(__dirname, 'predszapis-osen-ege-profilnoe/index.html'),
        'predszapis-osen-ege-bazovoe': resolve(__dirname, 'predszapis-osen-ege-bazovoe/index.html'),
        'shablon': resolve(__dirname, 'shablon/index.html'),
        'shablon-bez-geymifikatsii': resolve(__dirname, 'shablon-bez-geymifikatsii/index.html'),
        'dop-predmety-oge': resolve(__dirname, 'dop-predmety-oge/index.html'),
        'predzapis-avgust': resolve(__dirname, 'predzapis-avgust/index.html'),
        'avgust': resolve(__dirname, 'avgust/index.html'),
        'partnerskaya-programma-9-klass': resolve(__dirname, 'partnerskaya-programma-9-klass/index.html'),
        'partnerskaya-programma-9-klass-novoe': resolve(__dirname, 'partnerskaya-programma-9-klass-novoe/index.html'),
        'partnerskaya-programma-9-klass-bez-2-urokov': resolve(__dirname, 'partnerskaya-programma-9-klass-bez-2-urokov/index.html'),
        'podgotovka-k-oge': resolve(__dirname, 'podgotovka-k-oge/index.html'),
        'intellektualnyy-klub': resolve(__dirname, 'intellektualnyy-klub/index.html'),
        'samostoyatelnaya-oplata-osen': resolve(__dirname, 'samostoyatelnaya-oplata-osen/index.html'),
      },
    },
  },
  server: {
    port: 5173,
    open: true,
    allowedHosts: ['.ts.net'],
  },
})
